base_url = "https://ayukmr.com"

title = "ayukmr"
author = "Ayush Kumar"

compile_sass = true
generate_feeds = true

[[taxonomies]]
name = "tags"

[markdown]
smart_punctuation = true

highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "OneHalfLight", filename = "styles/syntax-light.css" },
    { theme = "OneHalfDark", filename = "styles/syntax-dark.css" },
]
